application: oscon-demo
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:

- url: /contacts
  script: contacts_example.php

- url: /oauth2callback
  script: contacts_example.php

#- url: .*
#  script: main.php
